# Generated by Django 6.0.8 on 2026-08-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(help_text='Duration (e.g. 45 mins)', max_length=50),
        ),
    ]
