# Generated by Django 6.0.8 on 2026-08-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_service_image_url_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='image_url',
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
    ]
