# Generated by Django 6.0.8 on 2026-08-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_package_image_url_package_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='code',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='offer',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='services_included',
            field=models.TextField(blank=True, help_text='Comma separated services'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='valid_until',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
