# Generated by Django 6.0.8 on 2026-08-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_payment_razorpay_order_id_payment_razorpay_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custom_service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
