# Generated by Django 6.0.8 on 2026-08-25 11:27

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_booking_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_address', models.TextField(default='123 Beauty Avenue, Anna Nagar, Chennai, Tamil Nadu 600040')),
            ],
        ),
    ]
