# Generated by Django 6.0.8 on 2026-08-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='booking_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='contact_number',
            field=models.CharField(default='+91 98765 43210', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='currency',
            field=models.CharField(default='INR (₹)', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='dashboard_mode',
            field=models.CharField(default='light', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='email_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='marketing_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='parlour_name',
            field=models.CharField(default='Sathya Beauty', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='sms_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='theme_color',
            field=models.CharField(default='pink', max_length=50),
        ),
    ]
