# Generated by Django 6.0.8 on 2026-08-26 13:06

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOTPVerification',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='api.adminuser')),
            ],
        ),
    ]
