# Generated by Django 6.0.8 on 2026-08-18 12:21

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_alter_contenttype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
